#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]
[[routes]]
pattern = "sublink-worker.mosyaf.web.id"
custom_domain = true
[[routes]]
pattern = "sublink.mosyaf.web.id"
custom_domain = true

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "42798afdefe9473cb7ba3b2ef6dc997c" }
]
